version: '3.8'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:MfDZk"rTtn[f>j%@localhost:3306/self-attendence
      PORT: 3000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB

  mysql:
    image: mysql:latest
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootUser#1234
      MYSQL_DATABASE: self-attendence
      MYSQL_USER: mcdonalds
      MYSQL_PASSWORD: MfDZk"rTtn[f>j%

networks:
  default:
