apiVersion: apps/v1
kind: Deployment
metadata:
  name: sst-api
  namespace: fiap-soat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sst-api
  template:
    metadata:
      labels:
        app: sst-api
    spec:
      initContainers:
      - name: migrate
        image: evilfeeh/self-service-totem:v2.1.6
        command: ["npm", "run", "migration:up"]
        envFrom:
        - secretRef:
            name: sst-api-secrets
        - configMapRef:
            name: sst-env
      containers:
      - name: sst-api
        image: evilfeeh/self-service-totem:v2.1.6
        env:
        - name: PORT
          value: '3000'
        - name: URL_DEPLOY
          value: http://34.95.232.166
        - name: URL_PAYMENT_API
          value: >-
            https://southamerica-east1-self-service-totem-428818.cloudfunctions.net/payment-fake
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: sst-api-secrets
        - configMapRef:
            name: sst-env
        startupProbe:
          httpGet:
            path: /api/docs
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 3
          failureThreshold: 30

        readinessProbe:
          httpGet:
            path: /api/docs
            port: 3000
          periodSeconds: 3
          failureThreshold: 1

        livenessProbe:
          httpGet:
            path: /api/docs
            port: 3000
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 1
          successThreshold: 1

        resources:
          limits:
            memory: 2Gi
            cpu: 2000m
          requests:
            memory: 128Mi
            cpu: 300m
