apiVersion: v1
kind: Service
metadata:
  name: sst-api
  namespace: fiap-soat
  labels:
    app: sst-api
spec:
  selector:
    app: sst-api
  type: LoadBalancer
  ports:
  - name: sst-api
    protocol: TCP
    port: 80
    targetPort: 3000
