apiVersion: v1
kind: PersistentVolume
metadata:
  name: sst-pv
  namespace: fiap-soat
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: fiap-soat
    name: sst-database-pvc
  hostPath:
    path: "/mnt/data"