apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: self-service-totem-database-sc
  resources:
    requests:
      storage: 256Mi