apiVersion: v1
kind: Service
metadata:
  name: sst-database
  namespace: fiap-soat
  labels:
    app: sst-database
spec:
  selector:
    app: sst-database
  clusterIP: None
  ports:
  - name: sst-database-port
    port: 80