apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sst-database
  namespace: fiap-soat
spec:
  selector:
    matchLabels:
      app: sst-database
  serviceName: database
  template:
    metadata:
      labels:
        app: sst-database
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 80
          name: sst-db-port
        readinessProbe:
          exec:
            command:
            - bin/sh
            - -c
            - > 
            - mysqladmin
            - ping
            - -h
            - localhost
            - -u
            - MYSQL_USER=$(printenv MYSQL_USER)
            - MYSQL_PASSWORD=$(printenv MYSQL_PASSWORD)
            - mysqladmin ping -h localhost -u MYSQL_USER -p MYSQL_PASSWORD
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /var/lib/sst-database-volume
          name: sst-database-volume
        envFrom:
        - secretRef:
            name: sst-database-secrets
  volumeClaimTemplates:
  - metadata:
      name: sst-database-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 512Mi
