apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sst-database-sc
  namespace: fiap-soat
  annotations:
    storageClass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/pce-pd
parameters:
  type: pd-standard
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
